version: "3"
services:
  kademlia:
    image: kadlab_dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    deploy:
      mode: replicated
      replicas: 5
      #        resources:
      #           limits:
      #              cpus: "0.1"
      #              memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    networks:
      - kademlia_dev_network
    volumes:
      - ./:/kademlia
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - K=5
      - ALPHA=1

networks:
  kademlia_dev_network:
