version: "3"
services:
  kademlia:
    image: kadlab 
    build:
      context: .
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 5  
#        resources:
#           limits:
#              cpus: "0.1"
#              memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
#    ports:
#      - "4000:80"
    networks:
      - kademlia_network
    command: ["run", "cmd/kademlia/kademlia.go"]
      
networks:
  kademlia_network:
