version: "3"
services:
  kademlia:
    image: kadlab_prod 
    build:
      context: .
      dockerfile: prod.Dockerfile
    deploy:
      mode: replicated
      replicas: 50  
#        resources:
#           limits:
#              cpus: "0.1"
#              memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    networks:
      - kademlia_network
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - K=5
      - ALPHA=3
      - LISTEN_PORT=1776
      - SEND_PORT=1777
      
networks:
  kademlia_network:
